#include "helper.h"
#include "visual.h"
#include <stdio.h>

void write_vtkFile_cavity(const char *szProblem,
		 int    timeStepNumber,
		 double xlength,
                 double ylength,
                 int    imax,
                 int    jmax,
		 double dx,
		 double dy,
                 double **U,
                 double **V,
								 double **P
							 ) {

  int i,j;
  char szFileName[80];
  FILE *fp=NULL;
  sprintf( szFileName, "%s.%i.vtk", szProblem, timeStepNumber );
  fp = fopen( szFileName, "w");
  if( fp == NULL )
  {
    char szBuff[80];
    sprintf( szBuff, "Failed to open %s", szFileName );
    ERROR( szBuff );
    return;
  }

  write_vtkHeader( fp, imax, jmax, dx, dy);
  write_vtkPointCoordinates(fp, imax, jmax, dx, dy);

  // fprintf(fp,"POINT_DATA %i \n", (imax+1)*(jmax+1) );
// fprintf(fp,"CELL_DATA %i \n", ((imax)*(jmax)) );
//   fprintf(fp,"\n");
//   fprintf(fp, "VECTORS velocity float\n");
//   for(j = 1; j <= jmax; j++) {
//     for(i = 1; i <= imax; i++) {
//       // fprintf(fp, "%f %f 0\n",0.5*(U[i+1][j]+U[i][j]),0.5*(V[i][j+1]+V[i][j]));
// 			fprintf(fp, "%f %f 0\n",0.5*(U[i][j]),V[i][j]);
//     }
//   }

fprintf(fp,"POINT_DATA %i \n", (imax+1)*(jmax+1) );

fprintf(fp,"\n");
fprintf(fp, "VECTORS velocity float\n");
for(j = 0; j <= jmax; j++) {
	for(i = 0; i <= imax; i++) {
		fprintf(fp, "%f %f 0\n", (U[i][j] + U[i][j+1]) * 0.5, (V[i][j] + V[i+1][j]) * 0.5 );
	}
}



	fprintf(fp,"\n");
  fprintf(fp,"CELL_DATA %i \n", ((imax)*(jmax)) );
	fprintf(fp, "SCALARS Pressure float 1 \n");
	fprintf(fp, "LOOKUP_TABLE default \n");
	for(j = 1; j < jmax+1; j++) {
		for(i = 1; i < imax+1; i++) {
			fprintf(fp, "%f\n", P[i][j] );
		}
	}

  if( fclose(fp) )
  {
    char szBuff[80];
    sprintf( szBuff, "Failed to close %s", szFileName );
    ERROR( szBuff );
  }
}

void write3D(
	const char *szProblem,
	int    timeStepNumber,
	double xlength,
	double ylength,
	int    imax,
	int    jmax,
	double dx,
	double dy,
	double k,
	double **MASS,
	double **XMOM,
	double **YMOM,
	double **ENER
)
{

	int i,j,kk;

	int kmax = 60;
	double pi = 3.14159265358979323846;
	double dz = 2*pi/kmax;

	char szFileName[80];
	FILE *fp=NULL;
	sprintf( szFileName, "%s.%i.vtk", szProblem, timeStepNumber );
	fp = fopen( szFileName, "w");
	if( fp == NULL )
	{
		char szBuff[80];
		sprintf( szBuff, "Failed to open %s", szFileName );
		ERROR( szBuff );
		return;
	}

	fprintf(fp,"# vtk DataFile Version 2.0\n");
	fprintf(fp,"generated by CFD-lab course output (written by Tobias Neckel) \n");
	fprintf(fp,"ASCII\n");
	fprintf(fp,"\n");
	fprintf(fp,"DATASET STRUCTURED_GRID\n");
	fprintf(fp,"DIMENSIONS  %i %i %i \n", imax+1, jmax+1,kmax+1);
	fprintf(fp,"POINTS %i float\n", (imax+1)*(jmax+1)*(kmax+1) );
	fprintf(fp,"\n");




	double originX = 0.0;
	double originY = 0.0;
	double originZ = 0.0;

	for (kk = 0; kk < kmax+1; kk++){
	  for(j = 0; j < jmax+1; j++) {
	    for(i = 0; i < imax+1; i++) {
	      // fprintf(fp, "%f %f 0\n", originX+(i*dx), originY+(j*dy) );
	      fprintf(fp, "%f %f %f\n", originX+(i*dx), originY+((j*dy)*sin(dz*kk)) ,originZ+(j*dy*cos(dz*kk)));
	    }
	  }
	}
	fprintf(fp,"\n");
	fprintf(fp,"CELL_DATA %i \n", (imax)*(jmax)*(kmax) );


	fprintf(fp, "VECTORS velocity float\n");

for (kk = 1; kk < kmax+1; kk++){
	for(j = 1; j < jmax+1; j++) {
		for(i = 1; i < imax+1; i++) {
			fprintf(fp, "%f %f 0\n",XMOM[i][j]/MASS[i][j],YMOM[i][j]/MASS[i][j]);
		}
	}
}
	if( fclose(fp) )
  {
    char szBuff[80];
    sprintf( szBuff, "Failed to close %s", szFileName );
    ERROR( szBuff );
  }
}


void write_vtkFile_ssc(const char *szProblem,
		 int    timeStepNumber,
		 double xlength,
                 double ylength,
                 int    imax,
                 int    jmax,
		 double dx,
		 double dy,
		 double k,
                 double **MASS,
                 double **XMOM,
                 double **YMOM,
							 	 double **ENER
							 ) {

  int i,j;
  char szFileName[80];
  FILE *fp=NULL;
  sprintf( szFileName, "%s.%i.vtk", szProblem, timeStepNumber );
  fp = fopen( szFileName, "w");
  if( fp == NULL )
  {
    char szBuff[80];
    sprintf( szBuff, "Failed to open %s", szFileName );
    ERROR( szBuff );
    return;
  }

  write_vtkHeader( fp, imax, jmax, dx, dy);
  write_vtkPointCoordinates(fp, imax, jmax, dx, dy);

  fprintf(fp,"CELL_DATA %i \n", (imax)*(jmax) );

  fprintf(fp,"\n");
  fprintf(fp, "VECTORS velocity float\n");
  for(j = 1; j < jmax+1; j++) {
    for(i = 1; i < imax+1; i++) {
      fprintf(fp, "%f %f 0\n",XMOM[i][j]/MASS[i][j],YMOM[i][j]/MASS[i][j]);
    }
  }

  fprintf(fp,"\n");
  /*fprintf(fp,"CELL_DATA %i \n", ((imax)*(jmax)) );*/
  fprintf(fp, "SCALARS pressure float 1 \n");
  fprintf(fp, "LOOKUP_TABLE default \n");
  for(j = 1; j < jmax+1; j++) {
    for(i = 1; i < imax+1; i++) {

      fprintf(fp, "%f\n", (ENER[i][j] - 0.5*(XMOM[i][j]*XMOM[i][j]+YMOM[i][j]*YMOM[i][j])/MASS[i][j])*(k-1));
    }
  }

	fprintf(fp,"\n");
  /*fprintf(fp,"CELL_DATA %i \n", ((imax)*(jmax)) );*/
	fprintf(fp, "SCALARS Density float 1 \n");
	fprintf(fp, "LOOKUP_TABLE default \n");
	for(j = 1; j < jmax+1; j++) {
		for(i = 1; i < imax+1; i++) {
			fprintf(fp, "%f\n", MASS[i][j] );
		}
	}

	fprintf(fp,"\n");
/*fprintf(fp,"CELL_DATA %i \n", ((imax)*(jmax)) );*/
fprintf(fp, "SCALARS Mach float 1 \n");
fprintf(fp, "LOOKUP_TABLE default \n");
for(j = 1; j < jmax+1; j++) {
	for(i = 1; i < imax+1; i++) {
		double P = (ENER[i][j] - 0.5*(XMOM[i][j]*XMOM[i][j]+YMOM[i][j]*YMOM[i][j])/MASS[i][j])*(k-1);
		double UX = XMOM[i][j]/MASS[i][j];
		double UY = YMOM[i][j]/MASS[i][j];
		double U = sqrt(UX*UX + UY*UY);
		double RHO = MASS[i][j];
		double MACH = U/sqrt(k*P/RHO);
		fprintf(fp, "%f\n", MACH );
	}
}

  if( fclose(fp) )
  {
    char szBuff[80];
    sprintf( szBuff, "Failed to close %s", szFileName );
    ERROR( szBuff );
  }
}


void write_vtkHeader( FILE *fp, int imax, int jmax,
                      double dx, double dy) {
  if( fp == NULL )
  {
    char szBuff[80];
    sprintf( szBuff, "Null pointer in write_vtkHeader" );
    ERROR( szBuff );
    return;
  }

  fprintf(fp,"# vtk DataFile Version 2.0\n");
  fprintf(fp,"generated by CFD-lab course output (written by Tobias Neckel) \n");
  fprintf(fp,"ASCII\n");
  fprintf(fp,"\n");
  fprintf(fp,"DATASET STRUCTURED_GRID\n");
  fprintf(fp,"DIMENSIONS  %i %i 1 \n", imax+1, jmax+1);
  fprintf(fp,"POINTS %i float\n", (imax+1)*(jmax+1) );
  fprintf(fp,"\n");
}


void write_vtkPointCoordinates( FILE *fp, int imax, int jmax,
                      double dx, double dy) {
  double originX = 0.0;
  double originY = 0.0;

  int i = 0;
  int j = 0;

  for(j = 0; j < jmax+1; j++) {
    for(i = 0; i < imax+1; i++) {
      fprintf(fp, "%f %f 0\n", originX+(i*dx), originY+(j*dy) );
    }
  }
}


void write_vtkFile_sw(const char *szProblem,
		 int    timeStepNumber,
		 double xlength,
                 double ylength,
                 int    imax,
                 int    jmax,
		 double dx,
		 double dy,
                 double **MASS
							 ) {

  int i,j;
  char szFileName[80];
  FILE *fp=NULL;
  sprintf( szFileName, "%s.%i.vtk", szProblem, timeStepNumber );
  fp = fopen( szFileName, "w");
  if( fp == NULL )
  {
    char szBuff[80];
    sprintf( szBuff, "Failed to open %s", szFileName );
    ERROR( szBuff );
    return;
  }

  write_vtkHeader( fp, imax, jmax, dx, dy);
  write_vtkPointCoordinates(fp, imax, jmax, dx, dy);

  fprintf(fp,"CELL_DATA %i \n", (imax)*(jmax) );


  fprintf(fp, "SCALARS Height float 1 \n");
  fprintf(fp, "LOOKUP_TABLE default \n");
  for(j = 1; j < jmax+1; j++) {
    for(i = 1; i < imax+1; i++) {

      fprintf(fp, "%f\n", (MASS[i][j]));
    }
  }


  if( fclose(fp) )
  {
    char szBuff[80];
    sprintf( szBuff, "Failed to close %s", szFileName );
    ERROR( szBuff );
  }
}
