#!/bin/bash

# Solid participant

# Run this script in one terminal and the fluid solver in another terminal.

# Use the precice-config for the serial run
ln -s -f precice_config_exchange1_implicit.xml precice-config.xml

# Prepare
blockMesh -case Solid_plate

# Run
laplacianFoam -case Solid_plate
